[General]
proxy-test-url = http://www.gstatic.com/generate_204

[Proxy]

[Remote Proxy]

[Remote Filter]
All_Filter = NameRegex, FilterKey = "."
AI_Filter = NameRegex, FilterKey = "\bAI\b"

[Proxy Group]
Proxy = select, Fallback, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Proxy.png
Fallback = fallback, Auto, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Available.png
Auto = url-test, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Auto.png
AI = url-test, AI_Filter, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Bot.png
Netflix = select, Proxy, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Netflix.png
# Microsoft = select, Proxy, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Microsoft.png
Final = select, Proxy, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Final.png

# https://github.com/blackmatrix7/ios_rule_script
[Remote Rule]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Advertising/Advertising.list, policy=REJECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/OpenAI/OpenAI.list, policy=AI, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Gemini/Gemini.list, policy=AI, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Claude/Claude.list, policy=AI, enabled=true
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Microsoft/Microsoft.list, policy=Microsoft, enabled=true
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Google/Google.list, policy=Proxy, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Apple/Apple.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/iCloud/iCloud.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Netflix/Netflix.list, policy=Netflix, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/China/China.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/China/China_Domain.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Lan/Lan.list, policy=DIRECT, enabled=true
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/ChinaIPs/ChinaIPs.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Global/Global.list, policy=Proxy, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Global/Global_Domain.list, policy=Proxy, enabled=true
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Direct/Direct.list, policy=DIRECT, enabled=true
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Proxy/Proxy.list, policy=Proxy, enabled=true

[Rule]
GEOIP,CN,DIRECT
FINAL,Final

[Rewrite]

[Host]

[Script]

[Mitm]
