[General]
ipv6 = false
dns-server = system,119.29.29.29,223.5.5.5
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,198.18.0.0/15,224.0.0.0/4,255.255.255.255/32
allow-udp-proxy = true
ssid-trigger = "default":rule,"cellular":rule

[Proxy]

[Remote Proxy]

[Remote Filter]
All_Filter = NameRegex, FilterKey = "."
AI_Filter = NameRegex, FilterKey = "GPT.*GM"

[Proxy Group]
Auto = url-test, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Auto.png
Proxy = select, Auto, All_Filter, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Proxy.png
AutoAI = url-test, AI_Filter, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50
AI = select, AutoAI, Proxy, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Bot.png
Netflix = select, Proxy, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Netflix.png
Microsoft = select, Proxy, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Microsoft.png
Final = select, Proxy, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Final.png

[Remote Rule]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Lan/Lan.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Advertising/Advertising.list, policy=REJECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/OpenAI/OpenAI.list, policy=AI, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Gemini/Gemini.list, policy=AI, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Claude/Claude.list, policy=AI, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Microsoft/Microsoft.list, policy=Microsoft, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Netflix/Netflix.list, policy=Netflix, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Apple/Apple.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/China/China.list, policy=DIRECT, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Global/Global.list, policy=Proxy, enabled=true

[Rule]
DOMAIN-SUFFIX,pairdrop.net,DIRECT
GEOIP,CN,DIRECT
FINAL,Final

[Rewrite]

[Host]

[Script]

[MITM]
skip-server-cert-verify = false
