#!MANAGED-CONFIG http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/api/file/Surfboard interval=86400

[General]
dns-server = 223.5.5.5, 119.29.29.29, 8.8.8.8
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
proxy-test-url = http://www.gstatic.com/generate_204

[Proxy]

[Proxy Group]
Proxy = select, Auto_EdNovas, Auto_TaiShan
Fallback = fallback, Auto_TimeLimited, Auto_NoExpiry
Auto_TimeLimited = url-test, Auto_EdNovas, Auto_TaiShan
Auto_NoExpiry = url-test, Auto_ShanHai, Auto_NightFury, Auto_CloudFisher
Auto_EdNovas = smart, policy-path = http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/download/A/Surfboard
Auto_TaiShan = smart, policy-path = http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/download/H/Surfboard
Auto_ShanHai = smart, policy-path = http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/download/B/Surfboard
Auto_NightFury = smart, policy-path = http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/download/G/Surfboard
# Auto_LiangXin = smart, policy-path = http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/download/D/Loon
Auto_CloudFisher = smart, policy-path = http://23.94.183.182:3000/MSVcvUiIFbMrjBZOTBBMAWrrLLTJLBxiKCDAOZrnaYC/download/C/Surfboard
AI = select, Proxy
Netflix = select, Proxy
Microsoft = select, Proxy, DIRECT
Final = select, Proxy, DIRECT

[Rule]
DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/private.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/reject.txt, REJECT
RULE-SET, SYSTEM, DIRECT

DOMAIN-SUFFIX, pairdrop.net, DIRECT
DOMAIN-SUFFIX, gh-proxy.com, DIRECT
DOMAIN-SUFFIX, ghfast.top, DIRECT
DOMAIN-SUFFIX, host.docker.internal, DIRECT

RULE-SET, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list, AI
RULE-SET, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list, AI
RULE-SET, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list, AI
RULE-SET, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list, Microsoft
RULE-SET, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list, Netflix

DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/icloud.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/apple.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/google.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/proxy.txt, Proxy, force-remote-dns
DOMAIN-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/direct.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/telegramcidr.txt, Proxy
RULE-SET, https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/cncidr.txt, DIRECT
RULE-SET, LAN, DIRECT
FINAL, Proxy, dns-failed